apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: client-api
  name: client-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - image: sukhdhaliwal/client:0.0.2
        imagePullPolicy: IfNotPresent
        name: client
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-api
  name: client-api
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8001
  selector:
    app: client-api

