apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: frontend-api
  name: frontend-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
        - image: sukhdhaliwal/frontend:0.0.8
          imagePullPolicy: IfNotPresent
          name: frontend
          envFrom:
            - configMapRef:
                name: booking-system
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-api
  name: frontend-api
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 3000
  selector:
    app: frontend-api
  type: ClusterIP
