spring:
  cloud:
    gateway:
      routes:
        - id: provider-id
          uri: lb://PROVIDER
          predicates:
            - Path=/provider/**
          filters:
            - AuthenticationFilter


        - id: client-id
          uri: lb://CLIENT
          predicates:
            - Path=/client/**
          filters:
            - AuthenticationFilter

        - id: identityService-id
          uri: lb://IDENTITYSERVICE
          predicates:
            - Path=/auth/**
