spring:
  cloud:
    gateway:
      routes:
        - id: frontend-protected-id
          uri: ${FRONTEND_URI:http://localhost:3000}
          predicates:
            - Path=/protected/**
          filters:
            - AuthenticationFilter

        - id: fronted-id
          uri: ${FRONTEND_URI:http://localhost:3000}
          predicates:
            - Path=/**
