apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: identity-service-api
  name: identity-service-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: identity-service-api
    spec:
      containers:
      - image: sukhdhaliwal/identity-service:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: identity-service
        envFrom:
          - configMapRef:
              name: booking-system
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-service-api
  name: identity-service-api
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: identity-service-api

