apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: appointment-api
  name: appointment-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: appointment-api
    spec:
      containers:
      - image: sukhdhaliwal/appointment:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: appointment
        envFrom:
          - configMapRef:
              name: booking-system
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: appointment-api
  name: appointment-api
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8010
  selector:
    app: appointment-api
  type: LoadBalancer

