apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: provider-api
  name: provider-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: provider-api
    spec:
      containers:
      - image: sukhdhaliwal/provider:0.0.3
        imagePullPolicy: IfNotPresent
        name: provider
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: provider-api
  name: provider-api
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    app: provider-api



